### ISSUE TITLE
No licence

### ISSUE THREAD

**Issue by drewsilcock** [azer/go-makefile-example#8]
This makefile is really super cool, but there's no licence associated with this project which legally means the default "all rights reserved" applies. (See [GitHub licensing help pages for more info](https://help.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository#choosing-the-right-license).)

If you could add an open source licence like MIT (or whichever), that would allow those of us working in places with policies about licensing to use it.

**Comment by azer** [comment]
added license

**Comment by drewsilcock** [comment]
Thanks
